FROM apache/airflow:2.9.3-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

# Провайдер Postgres (нужен для PostgresOperator/Hook) + psycopg2
RUN pip install --no-cache-dir "apache-airflow-providers-postgres>=5.10.0"
